apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "perfsonar-testpoint.fullname" . }}
  labels:
    app: {{ template "perfsonar-testpoint.name" . }}
    chart: {{ template "perfsonar-testpoint.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "perfsonar-testpoint.name" . }}
      chart: {{ template "perfsonar-testpoint.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance | quote }}
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ template "perfsonar-testpoint.name" . }}
        chart: {{ template "perfsonar-testpoint.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance | quote }}
    spec:
      hostNetwork: true
      containers:
      - name: perfsonar-testpoint
        {{ if .Values.psconfigURL }}
        command: ["psconfig", "remote", "add"]
        args: {{ .Values.psconfigURL }}
        {{ end }}
        image: perfsonar/testpoint:4.2.4
        imagePullPolicy: Always
        securityContext: 
          privileged: true
      restartPolicy: Always
      {{ if .Values.nodeSelection }}
      nodeSelector:
        perfsonar: enabled
      {{ end }}
status: {}
