{{ if .Values.SecurityNetworkPolicy.Enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "minio.fullname" . }}
  labels:
    app: {{ template "minio.name" . }}
    chart: {{ template "minio.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "minio.name" . }}
      chart: {{ template "minio.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance | quote }}
  policyTypes:
  - Ingress
  - Egress
  egress:
  - to:
    {{- range .Values.SecurityNetworkPolicy.AllowedCIDRs}}
    - ipBlock:
        cidr: {{ . }}
    {{- end }}
  ingress:
  - from:
    {{- range .Values.SecurityNetworkPolicy.AllowedCIDRs}}
    - ipBlock:
        cidr: {{ . }}
    {{- end }}
{{ end }}
