# Default values for perfsonar-testpoint.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

Instance: ''
#Allows for the creation a a network policy that limits what cidrs can access this app
#By default it is turned off
#Default allowed cidr will create an allow all policy
NetworkPolicy:
  Enabled: false
  AllowedCIDRs:
    - 0.0.0.0/0

# Whether to run only on specially marked nodes. 
# If nodeSelection is true, this service will only run on a node
# which has the `perfsonar: enabled` label applied to it. 
# Otherwise, it will allow itself to be scheduled on any node. 
nodeSelection: false
