{{ if .Values.NetworkPolicy.Enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "master.fullname" . }}-network-policy
  labels:
    app: {{ template "mariadb.name" . }}
    chart: {{ template "mariadb.chart" . }}
    release: {{ .Release.Name | quote }}
    instance: {{ .Values.Instance | quote }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "mariadb.name" . }}
      chart: {{ template "mariadb.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance | quote }}
  policyTypes:
  - Ingress
  - Egress
  egress:
  - to:
    {{- range .Values.NetworkPolicy.AllowedCIDRs}}
    - ipBlock:
        cidr: {{ . }}
    {{- end }}
  ingress:
  - from:
    {{- range .Values.NetworkPolicy.AllowedCIDRs}}
    - ipBlock:
        cidr: {{ . }}
    {{- end }}
{{ end }}
